VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #config.vm.memory = 2048
  config.vm.box = "acompli/devops-test"
  config.vm.box_url = [
    "https://s3.amazonaws.com/assets.acompli.net/vagrant/devops-test.box"
  ]
    
  config.vm.network "forwarded_port", guest: 80, host: 8080    # Apache HTTP
  config.vm.network "forwarded_port", guest: 443, host: 443   # Apache HTTPS
  config.vm.network "forwarded_port", guest: 5000, host: 5000  # Flask debug server
  
  config.vm.provision "file", source: "files/site.conf", destination: "/tmp/site.conf"
  config.vm.provision "shell", path: "files/provision.sh"
  #config.vm.boot_timeout = 1000
  
  #config.vm.synced_folder "#{ENV['HOME']}/devops-test-share", "/var/www/devops-test-share", create: true
  
  #config.vm.provider "virtualbox" do |vb|
   #vb.gui = true
  
end
